modLoader="javafml"
loaderVersion="[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/EclipsedReaper/persistent-options/issues"

[[mods]]
modId = "persistent_options"
version = "${version}"
displayName = "Persistent Options"
author = "EclipsedReaper"
description = "Keeps your options in a global folder so you don't have to change them every time"
logoFile = "assets/persistent_options/icon.png"

[[dependencies.persistent_options]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.persistent_options]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.4]"
ordering="NONE"
side="BOTH"

[[dependencies.persistent_options]]
modId="architectury"
mandatory=true
versionRange="[9.2.14,)"
ordering="NONE"
side="BOTH"