modLoader = "javafml"
loaderVersion = "[1,)"
license = "CC0-1.0"
issueTrackerURL = "https://github.com/.../persistent-options/issues"

[[mods]]
modId = "persistent_options"
version = "${version}"
displayName = "Persistent Options"
author = "EclipsedReaper"
description = "Keeps your options in a global folder so you don't have to change them every time"
logoFile = "assets/persistent_options/icon.png"

[[dependencies.persistent_options]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4, 1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.persistent_options]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.persistent_options]]
modId = "architectury"
type = "required"
versionRange = "[9,)"
ordering = "AFTER"
side = "BOTH"